# Generated by Django 4.1.2 on 2022-11-03 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='titulo')),
                ('autor', models.CharField(max_length=30, verbose_name='autor')),
                ('sinopse', models.TextField(verbose_name='autor')),
                ('ano_publicacao', models.DateField(verbose_name='Ano de publicação')),
                ('escola', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livro.escola')),
            ],
        ),
    ]
