# Generated by Django 4.1.2 on 2022-11-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='ano_publicacao',
        ),
        migrations.AddField(
            model_name='livro',
            name='data_publicacao',
            field=models.DateField(default=None, verbose_name='Data de publicação'),
        ),
        migrations.AddField(
            model_name='livro',
            name='preco',
            field=models.FloatField(default=0, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(verbose_name='sinópse'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='título'),
        ),
    ]
