# Generated by Django 4.1.2 on 2022-11-19 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_remove_livro_ano_publicacao_livro_data_publicacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_publicacao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de publicação'),
        ),
    ]
