# Generated by Django 4.1.2 on 2022-11-19 15:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livro', '0002_remove_livro_ano_publicacao_livro_data_publicacao_and_more'),
        ('usuario', '0002_alter_preferencias_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preferencias',
            new_name='Preferencia',
        ),
    ]
