# Generated by Django 4.1.2 on 2022-11-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_rename_preferencias_preferencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferencia',
            old_name='preferencia',
            new_name='escola',
        ),
    ]
